import { z } from 'zod'

export const fragmentSchema = z.object({
  commentary: z
    .string()
    .describe(
      `Describe what you're about to do and the steps you want to take for generating the fragment in great detail.`,
    ),
  template: z
    .string()
    .describe('Name of the template used to generate the fragment.'),
  // template_ready: z.boolean().describe('Detect if finished identifying the template.'),
  title: z.string().describe('Short title of the fragment. Max 3 words.'),
  description: z
    .string()
    .describe('Short description of the fragment. Max 1 sentence.'),
  additional_dependencies: z
    .array(z.string())
    .describe(
      'Additional dependencies required by the fragment. Do not include dependencies that are already included in the template.',
    ),
  has_additional_dependencies: z
    .boolean()
    .describe(
      'Detect if additional dependencies that are not included in the template are required by the fragment.',
    ),
  install_dependencies_command: z
    .string()
    .describe(
      'Command to install additional dependencies required by the fragment.',
    ),
  // install_dependencies_ready: z.boolean().describe('Detect if finished identifying additional dependencies.'),
  port: z
    .number()
    .nullable()
    .describe(
      'Port number used by the resulted fragment. Null when no ports are exposed.',
    ),
  file_path: z
    .string()
    .describe('Relative path to the file, including the file name.'),
  code: z
    .string()
    .describe('Code generated by the fragment. Only runnable code is allowed.'),
  // code: z.array(z.object({
  //   file_name: z.string().describe('Name of the file.'),
  //   file_path: z.string().describe('Relative path to the file, including the file name.'),
  //   file_content: z.string().describe('Content of the file.'),
  //   file_finished: z.boolean().describe('Detect if finished generating the file.'),
  // })),
  // code_finished: z.boolean().describe('Detect if finished generating the code.'),
  // error: z.string().optional().describe('Error message if the fragment is not valid.'),
})

export type FragmentSchema = z.infer<typeof fragmentSchema>

// Schema for morph edit instructions
export const morphEditSchema = z.object({
  commentary: z
    .string()
    .describe('Explain what changes you are making and why'),
  instruction: z
    .string()
    .describe('One line instruction on what the change is'),
  edit: z
    .string()
    .describe(
      "You should make it clear what the edit is, while also minimizing the unchanged code you write. When writing the edit, you should specify each edit in sequence, with the special comment // ... existing code ... to represent unchanged code in between edited lines. For example: // ... existing code ... FIRST_EDIT // ... existing code ... SECOND_EDIT // ... existing code ... THIRD_EDIT // ... existing code ... Be Lazy when outputting code, rely heavily on the exisitng code comments, but each edit should contain minimally sufficient context of unchanged lines around the code you're editing to resolve ambiguity. DO NOT omit spans of pre-existing code (or comments) without using the // ... existing code ... comment to indicate its absence. If you omit the existing code comment, the model may inadvertently delete these lines. If you plan on deleting a section, you must provide context before and after to delete it. If the initial code is ```code \\n Block 1 \\n Block 2 \\n Block 3 \\n code```, and you want to remove Block 2, you would output ```// ... existing code ... \\n Block 1 \\n  Block 3 \\n // ... existing code ...```. ",
    ),
  file_path: z.string().describe('Path to the file being edited'),
})

export type MorphEditSchema = z.infer<typeof morphEditSchema>

// ── Resume Content Schema ────────────────────────────────────────────────
// Used when the app is in RESUME_MODE. The model emits structured resume
// sections that the <ResumeArtifact /> renders dynamically.

export type ResumeItem = {
  id?: string
  label: string
  value?: string
  detail?: string
  tags?: string[]
  url?: string
  children?: ResumeItem[]
}

export const resumeItemSchema: z.ZodType<ResumeItem> = z.lazy(() =>
  z.object({
    id: z.string().optional().describe('Stable kebab-case id for this item'),
    label: z.string().describe('Title or label for the item.'),
    value: z.string().optional().describe('Short value or description.'),
    detail: z.string().optional().describe('Longer explanation or bullet point.'),
    tags: z.array(z.string()).optional().describe('Small tags/badges, e.g. tech stack or dates.'),
    url: z.string().optional().describe('Optional link URL.'),
    children: z
      .array(resumeItemSchema)
      .optional()
      .describe('Hierarchical drill-down details for this item'),
  }),
)

export const resumeSectionTypeSchema = z.enum([
  'highlights',
  'experience',
  'projects',
  'skills',
  'education',
  'certifications',
  'summary',
])
export type ResumeSectionType = z.infer<typeof resumeSectionTypeSchema>

export const resumeSectionIdSchema = z
  .string()
  .min(2)
  .max(80)
  .regex(/^[a-z0-9][a-z0-9-]*$/, {
    message:
      'Section id must be kebab-case, lowercase, and start with a letter or number (e.g. "summary", "experience-acme-2023", "skills-frontend").',
  })
  .describe(
    'Stable kebab-case id for the section. Reuse the same id when updating an existing section. New ids should be descriptive and unique within the sandbox.',
  )

export const resumeSectionSchema = z.object({
  id: resumeSectionIdSchema.describe('Stable kebab-case id'),
  type: resumeSectionTypeSchema.describe('Section type key.'),
  title: z.string().describe('Human-readable section title.'),
  items: z.array(resumeItemSchema).describe('Ordered list of items in this section.'),
})

export const resumeContentSchema = z.object({
  commentary: z
    .string()
    .describe('A warm, conversational response to the recruiter question.'),
  focus: z
    .string()
    .describe('Short phrase describing what this resume view is tuned for.'),
  sections: z
    .array(resumeSectionSchema)
    .describe(
      'Ordered resume sections. Omit sections that are not relevant to the question. Always include highlights + relevant sections — do not dump the full resume unless asked.',
    ),
})

export type ResumeItemSchema = z.infer<typeof resumeItemSchema>
export type ResumeSectionSchema = z.infer<typeof resumeSectionSchema>
export type ResumeContentSchema = z.infer<typeof resumeContentSchema>

// ── Resume Agent State Schema ─────────────────────────────────────────────
// Shared state between the CopilotKit agent and the UI: the full resume plus
// the ids of sections/items the agent touched in the last turn.

export const resumeAgentStateSchema = z.object({
  resume: resumeContentSchema,
  highlights: z
    .array(z.string())
    .default([])
    .describe('Ids of sections/items changed or expanded in the last turn'),
})
export type ResumeAgentState = z.infer<typeof resumeAgentStateSchema>

// ── Resume Sandbox Patch Schema ───────────────────────────────────────────
// The model emits a patch against the current sandbox, not a full resume.
// The client merges the patch into the local sandbox and renders the result.

export const resumeSectionWithIdSchema = z.object({
  id: resumeSectionIdSchema,
  type: resumeSectionTypeSchema,
  title: z.string(),
  items: z.array(resumeItemSchema),
})

export const resumeSectionUpdateSchema = z.object({
  id: resumeSectionIdSchema.describe('The id of an existing section to update.'),
  type: resumeSectionTypeSchema.optional(),
  title: z.string().optional(),
  items: z.array(resumeItemSchema).optional().describe('Replaces the section items.'),
})

export const resumeSectionReorderSchema = z.object({
  id: resumeSectionIdSchema,
  position: z.number().int().min(0).describe('New order position. Lower comes first.'),
})

export const resumePatchOpSchema = z
  .object({
    add: z
      .array(resumeSectionWithIdSchema)
      .optional()
      .describe(
        'Sections to add. Each must have a unique id that does not exist in the current sandbox.',
      ),
    update: z
      .array(resumeSectionUpdateSchema)
      .optional()
      .describe('Sections to update by id. Omitted fields are preserved.'),
    remove: z
      .array(resumeSectionIdSchema)
      .optional()
      .describe('Section ids to remove from the sandbox.'),
    reorder: z
      .array(resumeSectionReorderSchema)
      .optional()
      .describe('Section ids to move to a new position.'),
  })
  .describe(
    'Patch operations to apply to the sandbox. An empty patch is valid and means: keep the sandbox as-is and just respond.',
  )

export const resumePatchSchema = z.object({
  commentary: z
    .string()
    .describe('A warm, conversational response to the recruiter question.'),
  intent: z
    .string()
    .describe(
      'Short phrase (3-8 words) describing what the user asked for. Used to label the orchestration history.',
    ),
  focus: z
    .string()
    .describe(
      'Short phrase (2-5 words) describing what the current resume view is tuned for. Drives the right-panel header.',
    ),
  patch: resumePatchOpSchema,
})

export type ResumeSectionWithIdSchema = z.infer<typeof resumeSectionWithIdSchema>
export type ResumeSectionUpdateSchema = z.infer<typeof resumeSectionUpdateSchema>
export type ResumeSectionReorderSchema = z.infer<typeof resumeSectionReorderSchema>
export type ResumePatchOpSchema = z.infer<typeof resumePatchOpSchema>
export type ResumePatchSchema = z.infer<typeof resumePatchSchema>
